name: CI

on: [push]

jobs:
  build:
    runs-on: stronglytyped/arm-none-eabi-gcc

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        run: make

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Test
        run: |
          make check
