name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: stronglytyped/arm-none-eabi-gcc

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: List files in the repository
        run: |
          find ${{ github.workspace }}
      - name: Build
        run: make

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test
        run: |
          make check
