name: CI

on: [push, pull_request]

env:
  CONTAINER: stronglytyped/arm-none-eabi-gcc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Start Docker Container
            run: |
              docker pull $CONTAINER
              docker run --name build-container -d -v ${{ github.workspace }}:/workspace $CONTAINER tail -f /dev/null

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Dump versions
        run: |
          lsb_release -a 2>/dev/null || cat /etc/issue
          git --version
          make --version
          cmake --version
          gcc --version
          g++ --version
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Check out ticdecodecpp submodule
        run: |
          git submodule init ticdecodecpp
          git submodule update
      - name: Test
        run: |
          make check
